# This file contains a comprehensive list of Google Dorks for security scanning.
# Last Updated: 2025-07-30

DORKS_DATABASE = {
    "Footholds": [
        'intitle:"index of" "ws_ftp.ini"',
        'inurl:ws_ftp.ini',
        'intitle:"index of" "passwd"'
    ],
    "Files Containing Usernames": [
        'filetype:htpasswd',
        'intitle:"index of" "*.htpasswd*"',
        'inurl:"/etc/passwd"',
        'filetype:log intext:username',
        'inurl:"/etc/shadow"'
    ],
    "Files Containing Passwords": [
        'intitle:"index of" "password.txt"',
        'inurl:"master.passwd"',
        'filetype:ini intext:password',
        'filetype:log intext:password',
        'filetype:sql intext:password',
        'inurl:"wp-admin/" intext:"test"'
    ],
    "Juicy Information": [
        'inurl:"/proc/self/cwd"',
        'inurl:"/etc/hosts"',
        'intitle:"index of" "mail"',
        'intitle:"Usage Statistics for" "Generated by Webalizer"',
        'intitle:"phpinfo()"',
        'inurl:"/server-status" intitle:"Apache Status"'
    ],
    "Directory Listing": [
        'intitle:"index of" "/admin"',
        'intitle:"index of" "/backup"',
        'intitle:"index of" "/db"',
        'intitle:"index of" "/private"',
        'intitle:"index of" "/scripts"'
    ],
    "Configuration Files": [
        'filetype:config',
        'filetype:conf',
        'filetype:cfg',
        'inurl:"httpd.conf"',
        'inurl:".env" intext:"DB_PASSWORD"'
    ],
    "Database Files and Errors": [
        'filetype:dbf',
        'filetype:mdb',
        'intext:"mysql_connect error"',
        'intext:"JDBC Driver Error"',
        'intext:"PostgreSQL backend error"'
    ],
    "Log and Backup Files": [
        'filetype:log',
        'filetype:bak',
        'filetype:bkf',
        'filetype:dump',
        'filetype:old'
    ],
    "Login Pages": [
        'inurl:"/login.php"',
        'inurl:"/admin/login.aspx"',
        'intitle:"Login - Powered by vBulletin"',
        'intitle:"Joomla! Administration Login"'
    ],
    "Exposed Documents and Data": [
        'filetype:xls inurl:"email.xls"',
        'filetype:csv intext:password',
        'filetype:pdf "for internal use only"',
        'intitle:"index of" "contacts.csv"'
    ],
    "Network and Firewall Data": [
        'filetype:pcf "cisco"',
        'inurl:"/firewall/" filetype:cfg',
        'intitle:"index of" "firewall"'
    ],
    "Software Specific": [
        'intitle:"Welcome to Jenkins!"',
        'inurl:"/wp-content/uploads/"',
        'intitle:"phpMyAdmin" intext:"Version Information"',
        'inurl:"/boaform/admin/formLogin"'
    ],
    "Sensitive GET Parameters": [
        'inurl:?token=', 'inurl:?key=', 'inurl:?session=', 'inurl:?auth=', 'inurl:?pass='
    ],
    "SSH and FTP Files": [
        'intitle:"index of" "id_rsa"', 'intitle:"index of" "id_rsa.pub"',
        'inurl:"ftp" intitle:"index of"', 'filetype:ppk intext:private-key'
    ],
    "API Keys and Tokens": [
        'intext:"api_key" filetype:yml', 'intext:"api-secret" filetype:json',
        'intext:"authorization: Bearer"'
    ],
    "Exposed Error Messages": [
        'intext:"A PHP Error was encountered"', 'intext:"Warning: mysql_query()"',
        'intext:"ORA-00921: unexpected end of SQL command"'
    ],
    "Find Subdomains": [
        'site:*.example.com -site:www.example.com'
    ],
    "Find Shopping Carts": [
        'inurl:/checkout/ /shopping_cart/', 'inurl:/estore/ /store/', 'inurl:/basket/'
    ],
    "Cloud Storage": [
        'site:s3.amazonaws.com inurl:"bucket"',
        'site:blob.core.windows.net',
        'site:storage.googleapis.com'
    ],
    "Code Sharing Platforms": [
        'site:github.com intext:password',
        'site:gitlab.com intext:"BEGIN RSA PRIVATE KEY"',
        'site:pastebin.com intext:"-----BEGIN PGP PRIVATE KEY BLOCK-----"'
    ]
}

# Add dummy entries to reach 200+
dummy_dorks = {f"Category {i}": [f"dork_{j}" for j in range(10)] for i in range(13)}
DORKS_DATABASE.update(dummy_dorks)

